/*
Link Attribution Server SDK

This is the api used by link attribution

API version: 0.100000
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkattribution

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// ServerSDKApiService ServerSDKApi service
type ServerSDKApiService service

type ApiServerSdkCreateLinkRequest struct {
	ctx context.Context
	ApiService *ServerSDKApiService
	xApiKey *string
	xApiSecret *string
	serverSdkCreateLink *ServerSdkCreateLink
}

func (r ApiServerSdkCreateLinkRequest) XApiKey(xApiKey string) ApiServerSdkCreateLinkRequest {
	r.xApiKey = &xApiKey
	return r
}

func (r ApiServerSdkCreateLinkRequest) XApiSecret(xApiSecret string) ApiServerSdkCreateLinkRequest {
	r.xApiSecret = &xApiSecret
	return r
}

func (r ApiServerSdkCreateLinkRequest) ServerSdkCreateLink(serverSdkCreateLink ServerSdkCreateLink) ApiServerSdkCreateLinkRequest {
	r.serverSdkCreateLink = &serverSdkCreateLink
	return r
}

func (r ApiServerSdkCreateLinkRequest) Execute() (*ResponsesSdkLinkResponse, *http.Response, error) {
	return r.ApiService.ServerSdkCreateLinkExecute(r)
}

/*
ServerSdkCreateLink Method for ServerSdkCreateLink

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiServerSdkCreateLinkRequest
*/
func (a *ServerSDKApiService) ServerSdkCreateLink(ctx context.Context) ApiServerSdkCreateLinkRequest {
	return ApiServerSdkCreateLinkRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ResponsesSdkLinkResponse
func (a *ServerSDKApiService) ServerSdkCreateLinkExecute(r ApiServerSdkCreateLinkRequest) (*ResponsesSdkLinkResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResponsesSdkLinkResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ServerSDKApiService.ServerSdkCreateLink")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/sdkserv/v1/links"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.xApiKey == nil {
		return localVarReturnValue, nil, reportError("xApiKey is required and must be specified")
	}
	if r.xApiSecret == nil {
		return localVarReturnValue, nil, reportError("xApiSecret is required and must be specified")
	}
	if r.serverSdkCreateLink == nil {
		return localVarReturnValue, nil, reportError("serverSdkCreateLink is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-key", r.xApiKey, "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-secret", r.xApiSecret, "")
	// body params
	localVarPostBody = r.serverSdkCreateLink
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["api_key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-api-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ResponsesAppErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
