/*
Link Attribution Server SDK

This is the api used by link attribution

API version: 0.100000
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkattribution

import (
	"encoding/json"
)

// checks if the ResponsesSdkLinkResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesSdkLinkResponseData{}

// ResponsesSdkLinkResponseData struct for ResponsesSdkLinkResponseData
type ResponsesSdkLinkResponseData struct {
	SdkLinkData ResponsesSdkLink `json:"sdkLinkData"`
}

// NewResponsesSdkLinkResponseData instantiates a new ResponsesSdkLinkResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesSdkLinkResponseData(sdkLinkData ResponsesSdkLink) *ResponsesSdkLinkResponseData {
	this := ResponsesSdkLinkResponseData{}
	this.SdkLinkData = sdkLinkData
	return &this
}

// NewResponsesSdkLinkResponseDataWithDefaults instantiates a new ResponsesSdkLinkResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesSdkLinkResponseDataWithDefaults() *ResponsesSdkLinkResponseData {
	this := ResponsesSdkLinkResponseData{}
	return &this
}

// GetSdkLinkData returns the SdkLinkData field value
func (o *ResponsesSdkLinkResponseData) GetSdkLinkData() ResponsesSdkLink {
	if o == nil {
		var ret ResponsesSdkLink
		return ret
	}

	return o.SdkLinkData
}

// GetSdkLinkDataOk returns a tuple with the SdkLinkData field value
// and a boolean to check if the value has been set.
func (o *ResponsesSdkLinkResponseData) GetSdkLinkDataOk() (*ResponsesSdkLink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SdkLinkData, true
}

// SetSdkLinkData sets field value
func (o *ResponsesSdkLinkResponseData) SetSdkLinkData(v ResponsesSdkLink) {
	o.SdkLinkData = v
}

func (o ResponsesSdkLinkResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesSdkLinkResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sdkLinkData"] = o.SdkLinkData
	return toSerialize, nil
}

type NullableResponsesSdkLinkResponseData struct {
	value *ResponsesSdkLinkResponseData
	isSet bool
}

func (v NullableResponsesSdkLinkResponseData) Get() *ResponsesSdkLinkResponseData {
	return v.value
}

func (v *NullableResponsesSdkLinkResponseData) Set(val *ResponsesSdkLinkResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesSdkLinkResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesSdkLinkResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesSdkLinkResponseData(val *ResponsesSdkLinkResponseData) *NullableResponsesSdkLinkResponseData {
	return &NullableResponsesSdkLinkResponseData{value: val, isSet: true}
}

func (v NullableResponsesSdkLinkResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesSdkLinkResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


